version: '3.8'

services:
  primary:
    image: postgres:latest
    container_name: primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5433:5432"
    networks:
      - pg-network

  replica:
    image: postgres:latest
    container_name: replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      REPLICATE_FROM: primary
    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5434:5432"
    depends_on:
      - primary
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  primary_data:
  replica_data: